
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.FSharp.Gui
{
	public partial class CompilerOptionsPanelWidget
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label targetFrameworksLabel;
		
		private global::Gtk.ComboBox targetFrameworkComboBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.FSharp.Gui.CompilerOptionsPanelWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.FSharp.Gui.CompilerOptionsPanelWidget";
			// Container child MonoDevelop.FSharp.Gui.CompilerOptionsPanelWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.targetFrameworksLabel = new global::Gtk.Label ();
			this.targetFrameworksLabel.Name = "targetFrameworksLabel";
			this.targetFrameworksLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Target Framework:");
			this.hbox1.Add (this.targetFrameworksLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.targetFrameworksLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.targetFrameworkComboBox = global::Gtk.ComboBox.NewText ();
			this.targetFrameworkComboBox.Name = "targetFrameworkComboBox";
			this.hbox1.Add (this.targetFrameworkComboBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.targetFrameworkComboBox]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(10));
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
