
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.FSharp.Gui
{
	public partial class CompilerOptionsPanelWidget
	{
		private global::Gtk.Expander expander1;
		
		private global::Gtk.ComboBox targetFrameworkComboBox;
		
		private global::Gtk.Label GtkLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.FSharp.Gui.CompilerOptionsPanelWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.FSharp.Gui.CompilerOptionsPanelWidget";
			// Container child MonoDevelop.FSharp.Gui.CompilerOptionsPanelWidget.Gtk.Container+ContainerChild
			this.expander1 = new global::Gtk.Expander (null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.targetFrameworkComboBox = global::Gtk.ComboBox.NewText ();
			this.targetFrameworkComboBox.Name = "targetFrameworkComboBox";
			this.expander1.Add (this.targetFrameworkComboBox);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("GtkExpander");
			this.GtkLabel.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel;
			this.Add (this.expander1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
